### ISSUE TITLE
Console errors in safari

### ISSUE THREAD

**Issue by ccampbell** [steenk/nodepdatalist#2]
When you try to render out a datalist dynamically your MutationObserver checks 

``` javascript
if (n[i] instanceof HTMLDataListElement) {
```

This causes the following console error

```
[Error] ReferenceError: Can't find variable: HTMLDataListElement
    (anonymous function) (datalist.js, line 86)
    forEach ([native code], line 0)
    (anonymous function) (datalist.js, line 72)
```

I think this if block should be removed completely because it is inside of 

``` javascript
if (typeof HTMLDataListElement === 'undefined') {
```

Therefore there is no way it can ever be defined on line 86 which means the `instanceof` check will fail

**Comment by steenk** [comment]
@ccampbell, thank you for notice this. I will look into it.

**Comment by bhanuV** [comment]
``` javascript
if (n[i] instanceof HTMLDataListElement) {
```

block was removed from the nodepdatalist which caused the console error on Safari
